name: bob_hacks
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  file_picker: ^8.0.0+1
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  size_config: ^2.0.3
  syncfusion_flutter_charts: ^26.2.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  webview_flutter: ^4.7.0
  flutter_pdfview: ^1.2.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0  
  hive_generator: ^2.0.1
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

 
    
  fonts:
    - family: 's'
      fonts:
        - asset: fonts/Roboto-Regular.ttf
  assets:
    - assets/svgs/
    - assets/jpgs/
    - assets/pngs/
    - assets/pdfs/pdf_1.pdf